import Testing

@testable import AdventOfCode

struct Day07Tests {
  // Smoke test data provided in the challenge question
  let testData = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

  @Test func testPart1() async throws {
    let challenge = Day07(data: testData)
    #expect(String(describing: challenge.part1()) == "21")
  }

  @Test func testPart2() async throws {
    let challenge = Day07(data: testData)
    #expect(String(describing: challenge.part2()) == "40")
  }
}
